### SignUp
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "username": "testuser10",
  "password": "test1234",
  "status": "PREMIUM"
}

### SignIn
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "username": "testuser10",
  "password": "test1234"
}
