### GetAll
GET http://localhost:3000/items

### findById
GET http://localhost:3000/items/cf98d4ac-81c4-4b42-8a68-1ca514e9169a

### Post
POST http://localhost:3000/items
Content-Type: application/json

{
  "name": "",
  "price": 0,
  "description": "とても綺麗です"
}

### Update
PUT http://localhost:3000/items/test2

### Delete
DELETE http://localhost:3000/items/test2